version: '3.7'

services:
  pyvvo:
    image: gridappsd-pyvvo
    environment:
      GRIDAPPSD_URI: tcp://gridappsd:61613
    depends_on:
      - gridappsd

  mysql-pyvvo:
    image: mysql/mysql-server:5.7
    ports:
      - 3307:3306

    environment:
      MYSQL_ROOT_PASSWORD: "pyvvo"
      MYSQL_DATABASE: "pyvvo"
      MYSQL_USER: "pyvvo"
      MYSQL_PASSWORD: "pyvvo"

    volumes:
      - type: bind
        source: ./mysql.cnf
        target: /etc/my.cnf

  blazegraph:
    image: gridappsd/blazegraph${GRIDAPPSD_TAG}
    ports:
      - 8889:8080

  redis:
    image: redis:3.2.11-alpine
    ports:
      - 6379:6379

    volumes:
      - ./gridappsd/redis/data:/data
    entrypoint: redis-server --appendonly yes

  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - 3306:3306

    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_PORT: 3306

    volumes:
      - ./gridappsdmysql:/var/lib/mysql
      - ./dumps/gridappsd_mysql_dump.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  viz:
    image: gridappsd/viz${GRIDAPPSD_TAG}
    ports:
      - 8080:8082

    depends_on:
      - gridappsd

  gridappsd:
    image: gridappsd/gridappsd${GRIDAPPSD_TAG}
    ports:
      # Each of the following are port mappings from the host into the
      # container.  The first three are used by GridAPPS-D for the different
      # protocols.
      - 61613:61613
      - 61614:61614
      - 61616:61616
      # Uncomment to allow debugging on this port
      - 8000:8000
      # Add debugging to your application via the following port
      - 8888:8888

    working_dir: /gridappsd
    environment:
      - PATH=/gridappsd/bin:/gridappsd/lib:/gridappsd/services/fncsgossbridge/service:$PATH
      # Debugging is only necessary if you intend to remote debug the GridAPPS-D process iself.
      # Turning this on will allow the user to remote debug the gridappsd server on port 8000.
      - DEBUG=1
# The following allow applications to be mounted into the container so that
# gridappsd can start them in the correct context.
#
# The format is local_path:container_path where local_path is on the host machine and the
# container_dir is inside the container.  The paths can be either a file or a directory.  In
# order for gridappsd to recognize it as an application the container path must be inside
# the /gridappsd/applications.  For services the container path must be inside /gridappsd/services.
#
# The following assumes you have cloned/downloaded the sample app in a sibling folder of this
# repository.  Once uncommenting the three lines below the sample_app will be available in the
# container
#
#    volumes:
#      - ~/git/gridappsd-sample-app/sample_app:/gridappsd/applications/sample_app
#      - ~/git/gridappsd-sample-app/sample_app/sample_app.config:/gridappsd/applications/sample_app.config

    depends_on:
      - mysql
      - blazegraph
      - redis

  proven:
    image: pnnl/proven:latest
    ports:
      - 18080:8080
    environment:
      # PROVEN_SERVICES_PORT - Proven service port [18080]
      # PROVEN_SWAGGER_HOST_PORT - Host and port value for Swagger (<host>:<port>)
      # PROVEN_USE_IDB - Use InfluxDB to save provenance metrics (true | false) [false]
      # PROVEN_IDB_URL - InfluxDB URL [http://localhost:8086]
      # PROVEN_IDB_DB - InfluxDB Database [proven]
      # PROVEN_IDB_RP - InfluxDB retention policy [autogen]
      # PROVEN_IDB_USERNAME - InfluxDb username [root]
      # PROVEN_IDB_PASSWORD - InfluxDb password [root]
      # PROVEN_T3DIR - directory location of triple store [user_home_directory]
      ####
      - PROVEN_SERVICES_PORT=18080
      - PROVEN_SWAGGER_HOST_PORT=localhost:18080
      - PROVEN_USE_IDB=true
      - PROVEN_IDB_URL=http://influxdb:8086
      - PROVEN_IDB_DB=proven
      - PROVEN_IDB_RP=autogen
      - PROVEN_IDB_USERNAME=root
      - PROVEN_IDB_PASSWORD=root
      - PROVEN_T3DIR=/proven

  influxdb:
    image: gridappsd/influxdb${GRIDAPPSD_TAG}
    environment:
      INFLUXDB_DB: "proven"
    ports:
      - 8086:8086

